services:
  ecommerce-db:
    container_name: ecommerce_postgres
    image: postgres
    environment:
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: ecommerce_pass
      PGDATA: /data/postgres
    volumes:
      - ecommerce_postgres_data:/data/postgres
    ports:
      - "5435:5432"
    networks:
      - ecommerce-network
    restart: unless-stopped

  ecommerce-pgadmin:
    container_name: ecommerce_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@ecommerce.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ecommerce_pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - ecommerce-network
    restart: unless-stopped

  ecommerce-mongodb:
    image: mongo
    container_name: ecommerce_mongodb
    ports:
      - "27017:27017"
    volumes:
      - ecommerce_mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=ecommerce_user
      - MONGO_INITDB_ROOT_PASSWORD=ecommerce_pass
    networks:
      - ecommerce-network
    restart: unless-stopped

  ecommerce-mongo-express:
    image: mongo-express
    container_name: ecommerce_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=ecommerce_user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=ecommerce_pass
      - ME_CONFIG_MONGODB_SERVER=ecommerce-mongodb
      - ME_CONFIG_MONGODB_URL=mongodb://ecommerce_user:ecommerce_pass@ecommerce-mongodb:27017/
    depends_on:
      - ecommerce-mongodb
    networks:
      - ecommerce-network
  mail-dev:
    container_name: ecommerce_maildev
    image: maildev/maildev
    ports:
      - "1080:1080"  # Web para ver correos
      - "1025:1025"  # SMTP para que tus apps envíen correos a este servidor
    networks:
      - ecommerce-network
    restart: unless-stopped
volumes:
  ecommerce_postgres_data:
  ecommerce_pgadmin_data:
  ecommerce_mongodb_data:

networks:
  ecommerce-network:
